### ISSUE TITLE
M.A.D Tank

### ISSUE THREAD

**Issue by DatOnePlayer** [NewestGitHubber/Commandustry#8]
Can you make an M.A.D Tank from Red Alert 1? It's a heavy suicide unit

**Comment by NewestGitHubber** [comment]
i have sprited the M.A.D tank, code for it should be going up soon 
please wait a few more hours ok? thanks

**Comment by DatOnePlayer** [comment]
Aightt!! :D

**Comment by NewestGitHubber** [comment]
the M.A.D Tank is now in Commandustry
